(async()=>{
 'use strict';
 const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];let token,data;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n/100);
 const date=v=>new Date(v).toLocaleString('ro-RO');
 async function request(url,payload){const response=await fetch('api/'+url,{method:payload?'POST':'GET',headers:{'X-Admin-Token':token,'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{}),cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Nu s-a putut salva.');return result;}
 function edit(product){const form=q('[data-product-editor]');form.reset();for(const name of ['id','name','kind','stock','image','description'])form.elements[name].value=product?.[name]??(name==='stock'?1:name==='kind'?'physical':name==='image'?'images/nava-studio.webp':'');form.elements.price.value=product?product.price/100:0;form.elements.active.checked=product?.active??true;form.elements.id.readOnly=!!product;q('[data-editor-status]').textContent='';if(innerWidth<721)form.scrollIntoView({behavior:'smooth',block:'start'});}
 function render(){q('[data-admin-products]').innerHTML=data.products.map(p=>'<article class="admin-product"><img src="'+esc(p.image)+'" alt="" width="75" height="65"><div><strong>'+esc(p.name)+'</strong><small>'+money(p.price)+' · '+p.stock+(p.stock===1?' unitate · ':' unități · ')+(p.active?'Vizibil':'Ascuns')+'</small></div><button class="button button-small button-ghost" type="button" data-edit="'+esc(p.id)+'">Editează</button></article>').join('');
 q('[data-admin-orders]').innerHTML=data.orders.length?data.orders.map(o=>'<article class="admin-record"><h3>'+esc(o.id)+'<small>'+date(o.createdAt)+'</small></h3><p>'+esc(o.customer.name)+' · '+esc(o.customer.email)+'<br>'+esc(o.customer.phone)+'<br>'+esc([o.customer.address,o.customer.city,o.customer.county].filter(Boolean).join(', '))+'</p><p>'+o.items.map(i=>esc(i.name)+' × '+i.quantity+' — '+money(i.price*i.quantity)).join('<br>')+'</p><p><strong>Total: '+money(o.total)+'</strong> · Livrare: '+esc({courier:'Curier',pickup:'Ridicare din atelier',digital:'Fișier digital'}[o.shipping]||o.shipping)+' · Fără plată</p>'+(o.notes?'<p>'+esc(o.notes)+'</p>':'')+'<label>Stare <select data-order-state="'+esc(o.id)+'">'+[['new','Nouă'],['processing','În lucru'],['completed','Finalizată demo'],['cancelled','Anulată']].map(([v,label])=>'<option value="'+v+'" '+(o.status===v?'selected':'')+'>'+label+'</option>').join('')+'</select></label></article>').join(''):'<div class="empty-state"><p>Nicio comandă încă. Încearcă fluxul din magazin cu date fictive.</p></div>';
 q('[data-admin-messages]').innerHTML=data.messages.length?data.messages.map(m=>'<article class="admin-record"><h3>'+esc(m.name)+'<small>'+date(m.createdAt)+'</small></h3><small>'+esc(m.id)+' · '+esc(m.service||'Fără serviciu ales')+'</small><p>'+esc(m.email)+' · '+esc(m.phone)+'</p><p>'+esc(m.message)+'</p><small>Salvat local. Email netrimis.</small></article>').join(''):'<div class="empty-state"><p>Niciun mesaj încă. Trimite o solicitare demo din pagina Contact.</p></div>';}
 async function reload(){data=await request('admin-data');render();}
 try{if(!['localhost','127.0.0.1','[::1]'].includes(location.hostname))throw Error('Administrarea demo este disponibilă doar local.');const response=await fetch('api/admin-session',{cache:'no-store'});if(!response.ok)throw Error('Pornește serverul: node dev-server.mjs, apoi deschide http://127.0.0.1:4174/admin.html.');token=(await response.json()).token;await reload();q('[data-admin-status]').textContent='Conectat local. Produsele sunt salvate în catalog; comenzile și mesajele rămân pe computer.';q('[data-admin-content]').hidden=false;edit(data.products[0]);}catch(error){q('[data-admin-status]').textContent=error.message;return;}
 qa('[data-admin-tab]').forEach(button=>button.addEventListener('click',async()=>{qa('[data-admin-tab]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});qa('[data-admin-panel]').forEach(p=>p.hidden=p.dataset.adminPanel!==button.dataset.adminTab);try{await reload();}catch(error){q('[data-admin-status]').textContent=error.message;}}));
 q('[data-admin-products]').addEventListener('click',event=>{const button=event.target.closest('[data-edit]');if(button)edit(data.products.find(p=>p.id===button.dataset.edit));});q('[data-new-product]').addEventListener('click',()=>edit());
 q('[data-product-editor]').addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(!form.reportValidity())return;const status=q('[data-editor-status]'),button=form.querySelector('[type=submit]');button.disabled=true;const values=Object.fromEntries(new FormData(form));try{await request('admin-products',{...values,price:Math.round(Number(values.price)*100),stock:Number(values.stock),active:form.elements.active.checked});await reload();form.elements.id.readOnly=true;status.textContent='Produs salvat. Modificarea este vizibilă în magazin după reîncărcare.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
 q('[data-admin-orders]').addEventListener('change',async event=>{const select=event.target.closest('[data-order-state]');if(!select)return;select.disabled=true;try{await request('admin-order',{id:select.dataset.orderState,status:select.value});window.crprintToast?.('Starea comenzii a fost salvată.');}catch(error){q('[data-admin-status]').textContent=error.message;}finally{select.disabled=false;}});
 q('[data-export-products]').addEventListener('click',()=>{const csvEscape=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['Type','SKU','Name','Published','Is featured?','Visibility in catalog','Short description','Description','In stock?','Stock','Regular price','Categories','Images'],...data.products.map(p=>[p.kind==='digital'?'simple, virtual, downloadable':'simple',p.id,p.name,-1,0,'visible',p.description,p.description,p.stock>0?1:0,p.stock,(p.price/100).toFixed(2),'Colecția navală',''])];const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(csvEscape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const href=URL.createObjectURL(blob),link=document.createElement('a');link.href=href;link.download='crprint-produse-draft.csv';link.click();setTimeout(()=>URL.revokeObjectURL(href),2000);});
})();
