(()=>{
 const q=s=>document.querySelector(s);let complete=[];
 try{complete=JSON.parse(localStorage.getItem('crprint-guide-progress')||'[]');}catch{}
 function progress(){q('[data-progress]').textContent=complete.length+'/10 capitole parcurse';q('progress').value=complete.length;const button=q('[data-complete]');const read=complete.includes(button.dataset.complete);button.textContent=read?'Capitol parcurs ✓ · Anulează marcarea':'Marchează capitolul ca parcurs ✓';button.setAttribute('aria-pressed',String(read));}
 progress();q('[data-complete]').addEventListener('click',event=>{const key=event.target.dataset.complete;complete=complete.includes(key)?complete.filter(x=>x!==key):[...complete,key];try{localStorage.setItem('crprint-guide-progress',JSON.stringify(complete));}catch{}progress();});
 q('.theme-button').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('crprint-guide-theme',theme);}catch{}});
 const search=q('#guide-search'),results=q('.search-results');let index=[];
 fetch('search-index.json').then(r=>r.json()).then(data=>index=data).catch(()=>{});
 const normalize=text=>text.toLocaleLowerCase('ro').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 search.addEventListener('input',()=>{const query=normalize(search.value.trim());results.replaceChildren();results.hidden=query.length<2;if(results.hidden)return;const found=index.filter(page=>normalize(page.title+' '+page.text).includes(query)).slice(0,10);if(!found.length){results.textContent='Niciun capitol găsit. Încearcă un cuvânt mai scurt.';return;}for(const page of found){const link=document.createElement('a');link.href=page.url;link.textContent=page.title;results.append(link);}});
 document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();search.focus();}});
 document.querySelectorAll('[data-launch-check]').forEach(input=>{const key='crprint-launch-'+input.dataset.launchCheck;try{input.checked=localStorage.getItem(key)==='1';}catch{}input.addEventListener('change',()=>{try{localStorage.setItem(key,input.checked?'1':'0');}catch{}});});
 const calculator=q('#budget-calculator');if(calculator){const f=n=>Number(calculator.elements[n].value)||0;const money=n=>new Intl.NumberFormat('ro-RO',{maximumFractionDigits:2}).format(n);function update(){const monthly=f('budget'),revenue=f('revenue'),cost=f('cost'),profit=f('profit'),rate=Math.min(100,Math.max(0,f('close')))/100;const contribution=revenue-cost,cpa=contribution-profit,cpl=cpa*rate;const output=q('#calculator-result');output.innerHTML='Medie zilnică Google orientativă: <strong>'+money(monthly/30.4)+' lei</strong><br>Marjă înainte de reclame: <strong>'+money(contribution)+' lei</strong><br>CPA maxim pentru profitul dorit: <strong>'+money(Math.max(0,cpa))+' lei</strong><br>CPL calificat orientativ: <strong>'+money(Math.max(0,cpl))+' lei</strong><br>'+ (cpa<=0?'Scenariul nu lasă buget pentru reclamă după profitul dorit. Ajustează prețul/costul.':'Praguri economice, fără promisiune de rezultate.');}calculator.addEventListener('input',update);update();}
})();
