(() => {
 'use strict';
 const key='crprint-cart-v2',q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
 const money=cents=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON',maximumFractionDigits:2}).format(cents/100);
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let cart=[],products=[],server=false,current;
 try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))cart=saved.filter(x=>typeof x.id==='string'&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100);}catch{}
 function save(){try{localStorage.setItem(key,JSON.stringify(cart));}catch{window.crprintToast?.('Browserul nu poate păstra coșul după închiderea paginii.');}updateCount();}
 function updateCount(){const count=cart.reduce((s,x)=>s+x.quantity,0);qa('[data-cart-count]').forEach(el=>el.textContent=count);qa('.cart-link').forEach(el=>el.setAttribute('aria-label','Coș de cumpărături, '+count+(count===1?' produs':' produse')));}
 updateCount();
 addEventListener('storage',event=>{if(event.key!==key)return;try{cart=JSON.parse(event.newValue||'[]');if(!Array.isArray(cart))cart=[];}catch{cart=[];}updateCount();if(products.length){renderCart();renderCheckout();}});
 const needsCatalog=q('[data-catalog],[data-product-price],[data-cart-items],[data-checkout-form],[data-price-id]');
 async function load(){try{const response=await fetch('api/products',{cache:'no-store'});if(!response.ok)throw Error();products=await response.json();if(!Array.isArray(products))throw Error('catalog');server=true;}catch{try{const response=await fetch('data/catalog.json',{cache:'no-store'});if(!response.ok)throw Error();const catalog=await response.json();if(!Array.isArray(catalog))throw Error('catalog');products=catalog.filter(x=>x.active);}catch{if(q('[data-catalog]'))q('[data-catalog]').textContent='Catalogul nu se poate încărca. Reîncarcă pagina sau contactează atelierul.';return;}}
  const filtered=cart.filter(x=>products.some(p=>p.id===x.id&&p.stock>0));if(filtered.length!==cart.length){cart=filtered;save();window.crprintToast?.('Coșul a fost actualizat: unele produse nu mai sunt disponibile.');}cart=cart.map(x=>({...x,quantity:Math.min(x.quantity,products.find(p=>p.id===x.id).stock,100)}));save();renderCatalog();initProduct();renderCart();renderCheckout();qa('[data-price-id]').forEach(el=>{const p=products.find(p=>p.id===el.dataset.priceId);el.textContent=p?money(p.price):'La cerere';});}
 function add(id,quantity=1){const p=products.find(x=>x.id===id);if(!p||p.stock<1)return window.crprintToast?.('Produsul nu este disponibil.');const amount=Math.max(1,Math.floor(Number(quantity)||1));const item=cart.find(x=>x.id===id);const existing=item?.quantity||0;const next=Math.min(p.stock,100,existing+amount);if(item)item.quantity=next;else cart.push({id,quantity:next});save();window.crprintToast?.(next<existing+amount?'Cantitatea a fost limitată la stocul disponibil.':'Produs adăugat în coș.');}
 function renderCatalog(){const host=q('[data-catalog]');if(!host)return;host.innerHTML=products.length?products.map(p=>'<article class="product-card"><a class="product-card-image" href="produs-nava.html?id='+encodeURIComponent(p.id)+'"><img src="'+esc(p.image)+'" alt="'+esc(p.name)+'" width="960" height="720" loading="lazy"><span class="product-kind">'+(p.kind==='digital'?'MODEL DIGITAL · FBX':'MACHETĂ PRINTATĂ')+'</span></a><div class="product-card-body"><h2><a href="produs-nava.html?id='+encodeURIComponent(p.id)+'">'+esc(p.name)+'</a></h2><p>'+esc(p.description)+'</p><div class="product-card-bottom"><strong>'+money(p.price)+'</strong><button class="button button-small button-ghost" type="button" data-add-id="'+esc(p.id)+'" '+(p.stock<1?'disabled':'')+'>'+(p.stock<1?'Indisponibil':'Adaugă +')+'</button></div></div></article>').join(''):'<p>Atelierul pregătește următoarele produse. Revino în curând.</p>';host.addEventListener('click',event=>{const button=event.target.closest('[data-add-id]');if(button)add(button.dataset.addId);});}
 function initProduct(){if(!q('[data-product-price]'))return;const requested=new URLSearchParams(location.search).get('id');current=products.find(p=>p.id===requested)||products.find(p=>p.id==='nava-24-septembrie');if(!current){q('.product-info').innerHTML='<h1>Produs indisponibil.</h1><a class="button button-primary" href="magazin.html">Vezi colecția ↗</a>';return;}
  const isShip=current.id.startsWith('nava-24-septembrie');if(!isShip){q('.variant-options').hidden=true;q('.gallery-thumbs').hidden=true;q('.product-3d').hidden=true;q('.product-info .eyebrow').textContent='DIN COLECȚIA ATELIERULUI';q('.product-layout>div>small').textContent='Imagine de prezentare a produsului.';}
  qa('[name=variant]').forEach(input=>{input.checked=input.value===current.id;const p=products.find(x=>x.id===input.value);input.disabled=!p||p.stock<1;input.addEventListener('change',()=>{const next=products.find(p=>p.id===input.value);if(next){current=next;updateProduct();}});});updateProduct();
  q('[data-add-product]')?.addEventListener('click',()=>{const field=q('[data-product-quantity]');if(!field.checkValidity())return field.reportValidity();add(current.id,field.value);});
  let galleryTimer;qa('[data-gallery]').forEach(button=>button.addEventListener('click',()=>{qa('[data-gallery]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const image=q('[data-product-image]');clearTimeout(galleryTimer);image.style.opacity='.3';galleryTimer=setTimeout(()=>{image.src='images/'+button.dataset.gallery+'.webp';image.onload=()=>image.style.opacity='1';},120);}));
 }
 function updateProduct(){q('[data-product-name]').textContent=current.name;q('[data-product-crumb]').textContent=current.name;q('[data-product-description]').textContent=current.description;q('[data-product-price]').textContent=money(current.price);q('[data-product-image]').src=current.image;q('[data-product-image]').alt='Prezentare: '+current.name;q('[data-product-stock]').textContent=current.stock>0?'Disponibil · '+current.stock+(current.stock===1?' unitate':' unități'):'Momentan indisponibil';const field=q('[data-product-quantity]');field.max=Math.min(100,current.stock);field.value=1;q('[data-add-product]').disabled=current.stock<1;q('[data-product-detail]').textContent=current.kind==='digital'?'Fișierul 3D în format FBX. Previzualizarea interactivă și imaginile îți arată geometria. Pentru întrebări despre utilizarea modelului, contactează atelierul.':'Macheta printată după modelul original. Pentru o scară, culoare sau finisare personalizată, discută cu atelierul înainte de comandă.';}
 const cartItems=()=>cart.map(item=>({...item,product:products.find(p=>p.id===item.id)})).filter(x=>x.product);
 const subtotal=()=>cartItems().reduce((n,x)=>n+x.quantity*x.product.price,0);
 function renderCart(){const host=q('[data-cart-items]');if(!host)return;const items=cartItems();q('[data-cart-empty]').hidden=items.length>0;q('[data-cart-filled]').hidden=!items.length;host.innerHTML=items.map(x=>'<article class="cart-item"><img src="'+esc(x.product.image)+'" alt="" width="110" height="90"><div><h2><a href="produs-nava.html?id='+encodeURIComponent(x.id)+'">'+esc(x.product.name)+'</a></h2><p>'+money(x.product.price)+' / '+(x.product.kind==='digital'?'fișier digital':'bucată')+'</p><div class="cart-controls"><label class="sr-only" for="qty-'+esc(x.id)+'">Cantitate pentru '+esc(x.product.name)+'</label><input id="qty-'+esc(x.id)+'" type="number" min="1" max="'+Math.min(x.product.stock,100)+'" value="'+x.quantity+'" data-cart-qty="'+esc(x.id)+'"><button class="remove-item" data-remove="'+esc(x.id)+'" type="button" aria-label="Elimină '+esc(x.product.name)+'">Elimină</button></div></div><strong>'+money(x.quantity*x.product.price)+'</strong></article>').join('');q('[data-cart-subtotal]').textContent=money(subtotal());}
 q('[data-cart-items]')?.addEventListener('change',event=>{const input=event.target.closest('[data-cart-qty]');if(!input)return;if(!input.checkValidity()){input.reportValidity();return;}const item=cart.find(x=>x.id===input.dataset.cartQty);if(item)item.quantity=Number(input.value);save();renderCart();});
 q('[data-cart-items]')?.addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(!button)return;cart=cart.filter(x=>x.id!==button.dataset.remove);save();renderCart();window.crprintToast?.('Produs eliminat din coș.');});
 function renderCheckout(){const form=q('[data-checkout-form]');if(!form)return;const items=cartItems();q('[data-checkout-empty]').hidden=!!items.length;q('[data-checkout-content]').hidden=!items.length;const physical=items.some(x=>x.product.kind==='physical');q('.shipping-options').hidden=!physical;q('[data-digital-notice]').hidden=physical;const shipping=physical&&form.elements.shipping.value==='courier'?1900:0;q('[data-shipping-fields]').hidden=!shipping;['address','city','county'].forEach(name=>form.elements[name].required=!!shipping);q('[data-checkout-items]').innerHTML=items.map(x=>'<div class="summary-item"><img src="'+esc(x.product.image)+'" alt="" width="60" height="55"><div>'+esc(x.product.name)+'<small>'+x.quantity+' × '+money(x.product.price)+'</small></div><strong>'+money(x.quantity*x.product.price)+'</strong></div>').join('');q('[data-checkout-subtotal]').textContent=money(subtotal());q('[data-checkout-shipping]').textContent=shipping?money(shipping):'Gratuit';q('[data-checkout-total]').textContent=money(subtotal()+shipping);}
 q('[data-checkout-form]')?.addEventListener('change',renderCheckout);
 let submitting=false,orderKey=globalThis.crypto?.randomUUID?.()||String(Date.now());
 q('[data-checkout-form]')?.addEventListener('submit',async event=>{event.preventDefault();if(submitting||!event.target.reportValidity())return;const form=event.target,button=form.querySelector('[type=submit]'),status=q('[data-checkout-status]');submitting=true;button.disabled=true;status.textContent='Se înregistrează comanda…';const values=Object.fromEntries(new FormData(form));const items=cartItems(),physical=items.some(x=>x.product.kind==='physical'),shipping=physical?values.shipping:'digital';let result;
  try{if(server){const response=await fetch('api/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':orderKey},body:JSON.stringify({items:cart,customer:values,shipping,notes:values.notes,idempotencyKey:orderKey})});result=await response.json();if(!response.ok)throw Error(result.error||'Comanda nu a putut fi salvată.');}else{result={id:'BROWSER-'+Date.now().toString(36).toUpperCase(),total:subtotal()+(shipping==='courier'?1900:0),shipping,demo:true};}
   const summary={id:result.id,total:result.total,shipping:result.shipping,server,hasDigital:items.some(x=>x.product.kind==='digital'&&x.id==='nava-24-septembrie-digital')};sessionStorage.setItem('crprint-last-order',JSON.stringify(summary));cart=[];save();location.assign('comanda-confirmata.html');
  }catch(error){status.textContent=error.message||'Nu s-a putut înregistra comanda. Încearcă din nou.';status.classList.add('is-error');submitting=false;button.disabled=false;}
 });
 function confirmation(){if(!q('[data-order-confirmation]'))return;let last;try{last=JSON.parse(sessionStorage.getItem('crprint-last-order')||'null');}catch{}if(!last)return;q('[data-order-confirmation]').hidden=false;q('[data-order-missing]').hidden=true;q('[data-order-id]').textContent=last.id;q('[data-order-total]').textContent=money(last.total);q('[data-order-storage]').textContent='Pentru întrebări, contactează atelierul și menționează referința comenzii.';q('[data-demo-download]').hidden=!last.hasDigital;}
 confirmation();if(needsCatalog)load();
})();
